/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.util.Set;
import login.V_NuevaCuenta;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class VentanaIncioSesion extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public VentanaIncioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbusuario = new javax.swing.JLabel();
        lbcontraseña = new javax.swing.JLabel();
        textoUsuario = new javax.swing.JTextField();
        logo = new javax.swing.JLabel();
        boton_login = new javax.swing.JButton();
        textopassword = new javax.swing.JPasswordField();
        btn_cuentaNueva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbusuario.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbusuario.setText("Usuario:");

        lbcontraseña.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbcontraseña.setText("Contraseña:");

        textoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuarioActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_twitter/twitter-removebg-preview (1).png"))); // NOI18N

        boton_login.setBackground(new java.awt.Color(88, 167, 246));
        boton_login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boton_login.setText("Log in");
        boton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_loginActionPerformed(evt);
            }
        });

        textopassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textopasswordActionPerformed(evt);
            }
        });

        btn_cuentaNueva.setBackground(new java.awt.Color(108, 176, 245));
        btn_cuentaNueva.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        btn_cuentaNueva.setText("No tienes cuenta?");
        btn_cuentaNueva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cuentaNuevaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbcontraseña)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(textopassword, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_cuentaNueva))
                    .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbusuario))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_login)
                .addGap(161, 161, 161))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lbusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lbcontraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textopassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(boton_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cuentaNueva)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_loginActionPerformed
        if (textoUsuario.getText().equals("") || textopassword.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Error! Debe de llenar todos los campos");
        } else {
            String usuario = textoUsuario.getText();
            String contraseña = textopassword.getText();

            usuario u = new usuario();
            boolean verificar = u.verificacionCuenta(usuario, contraseña);
            if (verificar == true) {
                JOptionPane.showMessageDialog(null, "Se ha iniciado sesion correctamente.");

                InicioSesion i = new InicioSesion();
                u.setUsuarioSesion(usuario);
                i.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "No se ha podido inciar sesion, intente de nuevo.");
            }
        }
    }//GEN-LAST:event_boton_loginActionPerformed

    private void btn_cuentaNuevaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cuentaNuevaMouseClicked
        V_NuevaCuenta V_NC = new V_NuevaCuenta();
        V_NC.setVisible(true);
        V_NC.setLocationRelativeTo(null);
        V_NC.setDefaultCloseOperation(2);

        this.dispose();
    }//GEN-LAST:event_btn_cuentaNuevaMouseClicked

    private void textopasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textopasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textopasswordActionPerformed

    private void textoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuarioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_login;
    private javax.swing.JButton btn_cuentaNueva;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbcontraseña;
    private javax.swing.JLabel lbusuario;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField textoUsuario;
    private javax.swing.JPasswordField textopassword;
    // End of variables declaration//GEN-END:variables
}
