/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Twitter;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class InicioTweets extends javax.swing.JFrame {

    /**
     * Creates new form InicioTweets
     */
    tweets t = new tweets();
    usuario u = new usuario();
    private ImageIcon imagenMasculinaI = new ImageIcon(getClass().getResource("/imagenes/ImagenMI.jpeg"));
    private ImageIcon imagenFemeninaI = new ImageIcon(getClass().getResource("/imagenes/ImagenFI.jpeg"));
    
    public InicioTweets() {
        initComponents();

        String[] tweetsFiltrados = t.tweetsFiltrados(u.getSeguidos(u.getUsuarioSesion()), u.getUsuarioSesion());
        listaTweets.setListData(tweetsFiltrados);
        String usuarioA= u.getUsuarioSesion();
        usuario usuarioActual=u.usersSearch(usuarioA);
        
        if (usuarioActual.genero== 'M') {
            pfpI.setIcon(imagenMasculinaI);
        } else {
            pfpI.setIcon(imagenFemeninaI);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buscarUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buscarHashtag = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();
        buscarMenciones = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTweets = new javax.swing.JList<>();
        usuarioActual = new javax.swing.JLabel();
        miPerfil = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textoTweet = new javax.swing.JTextField();
        publicarBoton = new javax.swing.JButton();
        pfpI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        buscarUsuario.setBackground(new java.awt.Color(0, 153, 255));
        buscarUsuario.setForeground(new java.awt.Color(0, 0, 0));
        buscarUsuario.setText("Buscar Usuario");
        buscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/twitter-removebg-preview (1).png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Twitter");
        jLabel1.setToolTipText("");

        buscarHashtag.setBackground(new java.awt.Color(0, 153, 255));
        buscarHashtag.setForeground(new java.awt.Color(0, 0, 0));
        buscarHashtag.setText("Buscar Hashtag");
        buscarHashtag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarHashtagActionPerformed(evt);
            }
        });

        cerrarSesion.setBackground(new java.awt.Color(0, 153, 255));
        cerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        cerrarSesion.setText("Cerrar sesion");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });

        buscarMenciones.setBackground(new java.awt.Color(0, 153, 255));
        buscarMenciones.setForeground(new java.awt.Color(0, 0, 0));
        buscarMenciones.setText("Mis Menciones");
        buscarMenciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMencionesActionPerformed(evt);
            }
        });

        listaTweets.setBackground(new java.awt.Color(204, 204, 204));
        listaTweets.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(listaTweets);

        usuarioActual.setForeground(new java.awt.Color(0, 153, 255));
        usuarioActual.setText("@"+usuario.usuarioSesion);

        miPerfil.setBackground(new java.awt.Color(0, 153, 255));
        miPerfil.setForeground(new java.awt.Color(0, 0, 0));
        miPerfil.setText("Mi Perfil");
        miPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPerfilActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Twitter Timeline");

        textoTweet.setBackground(new java.awt.Color(204, 204, 204));
        textoTweet.setForeground(new java.awt.Color(0, 0, 0));

        publicarBoton.setBackground(new java.awt.Color(0, 153, 255));
        publicarBoton.setForeground(new java.awt.Color(0, 0, 0));
        publicarBoton.setText("Publicar");
        publicarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(miPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarMenciones, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarHashtag, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 41, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(textoTweet, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(publicarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(108, 108, 108))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cerrarSesion)
                        .addGap(61, 61, 61))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(pfpI, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(349, 349, 349)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(usuarioActual)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cerrarSesion)
                        .addGap(41, 41, 41))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoTweet, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(publicarBoton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuarioActual)
                        .addGap(18, 18, 18)
                        .addComponent(pfpI, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(miPerfil)
                        .addGap(18, 18, 18)
                        .addComponent(buscarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(buscarMenciones)
                        .addGap(18, 18, 18)
                        .addComponent(buscarHashtag))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarMencionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMencionesActionPerformed
        // TODO add your handling code here:
        textoTweet.setText("");
        misMenciones mM=new misMenciones();
        mM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buscarMencionesActionPerformed

    private void publicarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicarBotonActionPerformed
        // TODO add your handling code here:
        //try{
        String contenidoTweet = textoTweet.getText();

        if (!contenidoTweet.isEmpty()) {
            boolean exito = t.publicarTweetUsuario(u.getUsuarioSesion(), contenidoTweet);
            if (exito) {
                JOptionPane.showMessageDialog(null, "El tweet ha sido publicado exitosamente!");
                String usuarioActual = u.getUsuarioSesion();
                
                String[] seguidos = u.getSeguidos(usuarioActual);
                String[] tweetsFiltrados = t.tweetsFiltrados(seguidos, usuarioActual);

                listaTweets.setListData(tweetsFiltrados);

            } else {
                JOptionPane.showMessageDialog(null, "No se pudo publicar el tweet!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "El espacio está vacío!");
        }
        //}catch(Exception e){
        //    JOptionPane.showMessageDialog(null, "Ingrese los datos adecuados para cada espacio.");
        //}
    }//GEN-LAST:event_publicarBotonActionPerformed

    private void miPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPerfilActionPerformed
        // TODO add your handling code here:
        //try{
        u.asignarUsuario(u.getUsuarioSesion());
        u.asignarNombre(u.getUsuarioSesion());
        u.asignarEdad(u.getUsuarioSesion());
        u.asignarGenero(u.getUsuarioSesion());
        u.asignarCantidadSeguidores(u.getUsuarioSesion());
        u.asignarCantidadSeguidos(u.getUsuarioSesion());
        u.asignarFecha(u.getUsuarioSesion());
        miPerfil mP = new miPerfil();
        mP.setVisible(true);
        this.dispose();
        //}catch(Exception e){
        //    JOptionPane.showMessageDialog(null, "Error!");
       // }
    }//GEN-LAST:event_miPerfilActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        // TODO add your handling code here:
        u.resetCerrarSesion();
        VentanaInicioSesion vIS = new VentanaInicioSesion();
        vIS.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void buscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUsuarioActionPerformed
        // TODO add your handling code here:
        try{
        busquedaUsuariosVentana bUV = new busquedaUsuariosVentana();
        bUV.setVisible(true);
        this.dispose();
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error!");
        }
    }//GEN-LAST:event_buscarUsuarioActionPerformed

    private void buscarHashtagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarHashtagActionPerformed
        // TODO add your handling code here:
        buscarHashtags bH=new buscarHashtags();
        bH.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buscarHashtagActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarHashtag;
    private javax.swing.JButton buscarMenciones;
    private javax.swing.JButton buscarUsuario;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaTweets;
    private javax.swing.JButton miPerfil;
    private javax.swing.JLabel pfpI;
    private javax.swing.JButton publicarBoton;
    private javax.swing.JTextField textoTweet;
    private javax.swing.JLabel usuarioActual;
    // End of variables declaration//GEN-END:variables
}
