/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Twitter;

import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class perfilUsuario extends javax.swing.JFrame {

    usuario u = new usuario();
    tweets tw = new tweets();

    /**
     * Creates new form perfilActual
     */
    public perfilUsuario() {
        initComponents();
        if (u.sigueOno(u.getUsuario())) {
        seguir.setText("Dejar de Seguir");
    } else {
        seguir.setText("Seguir");
    }
        
        if (u.getGenero() == 'M') {
            pfp.setIcon(u.imagenMasculina);
        } else {
            pfp.setIcon(u.imagenFemenina);
        }
        String usuarioA = u.getUsuario();
        String[] tweetsPerfilU = tw.tweetsPerfil(usuarioA);
        tweetsUsuario.setListData(tweetsPerfilU);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Seguidores = new javax.swing.JPanel();
        pfp = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        seguidoresUsuario = new javax.swing.JLabel();
        seguidosUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tweetsUsuario = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        seguir = new javax.swing.JButton();
        cerrarVentana = new javax.swing.JButton();
        genero = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Seguidores.setBackground(new java.awt.Color(255, 255, 255));

        pfp.setForeground(new java.awt.Color(0, 0, 0));

        Usuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Usuario.setForeground(new java.awt.Color(0, 0, 0));
        Usuario.setText("Usuario: @"+u.getUsuario());

        Nombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setText("Nombre: "+u.getNombre());

        seguidoresUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        seguidoresUsuario.setForeground(new java.awt.Color(0, 0, 0));
        seguidoresUsuario.setText("Seguidores: "+u.getCantidadSeguidores());

        seguidosUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        seguidosUsuario.setForeground(new java.awt.Color(0, 0, 0));
        seguidosUsuario.setText("Seguidos: "+u.getCantidadSeguidos());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Perfil");

        tweetsUsuario.setBackground(new java.awt.Color(204, 204, 204));
        tweetsUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tweetsUsuario);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tweets:");

        seguir.setBackground(new java.awt.Color(0, 153, 255));
        seguir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        seguir.setForeground(new java.awt.Color(0, 0, 0));
        seguir.setText("Seguir");
        seguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seguirActionPerformed(evt);
            }
        });

        cerrarVentana.setBackground(new java.awt.Color(0, 153, 255));
        cerrarVentana.setForeground(new java.awt.Color(0, 0, 0));
        cerrarVentana.setText("Cerrar");
        cerrarVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarVentanaActionPerformed(evt);
            }
        });

        genero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        genero.setForeground(new java.awt.Color(0, 0, 0));
        genero.setText("Genero: "+u.getGenero());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Fecha de Creacion: "+tw.formatoFecha());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/twitter-removebg-preview (1).png"))); // NOI18N

        javax.swing.GroupLayout SeguidoresLayout = new javax.swing.GroupLayout(Seguidores);
        Seguidores.setLayout(SeguidoresLayout);
        SeguidoresLayout.setHorizontalGroup(
            SeguidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeguidoresLayout.createSequentialGroup()
                .addGroup(SeguidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SeguidoresLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(pfp, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(SeguidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SeguidoresLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(SeguidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genero)
                            .addComponent(jLabel2)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seguidosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seguidoresUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SeguidoresLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SeguidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cerrarVentana)
                    .addComponent(seguir, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        SeguidoresLayout.setVerticalGroup(
            SeguidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeguidoresLayout.createSequentialGroup()
                .addGroup(SeguidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SeguidoresLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(SeguidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cerrarVentana)
                            .addComponent(jLabel4))
                        .addGap(12, 12, 12)
                        .addComponent(Nombre)
                        .addGap(18, 18, 18)
                        .addComponent(Usuario)
                        .addGap(18, 18, 18)
                        .addGroup(SeguidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SeguidoresLayout.createSequentialGroup()
                                .addComponent(seguidoresUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(seguidosUsuario))
                            .addComponent(seguir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(genero)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SeguidoresLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(pfp, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Seguidores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Seguidores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarVentanaActionPerformed
        // TODO add your handling code here:
        try {
            u.resetCantidadSeguidores();
            u.resetNombre();
            u.resetUsuario();
            u.resetCantidadSeguidos();
            u.resetEdad();
            u.resetGenero();

            InicioTweets iT = new InicioTweets();
            iT.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error!");
        }
    }//GEN-LAST:event_cerrarVentanaActionPerformed

    private void seguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seguirActionPerformed
        // TODO add your handling code here:
        try {
            String usuarioSesion = u.getUsuarioSesion();
            String usuarioSeguir = u.getUsuario();
            if (u.seguir(seguir, usuarioSesion, usuarioSeguir, seguidoresUsuario) == true) {
            } else if (u.dejarSeguir(seguir, usuarioSesion, usuarioSeguir, seguidoresUsuario) == true) {
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error!");
        }
    }//GEN-LAST:event_seguirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perfilUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nombre;
    private javax.swing.JPanel Seguidores;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton cerrarVentana;
    private javax.swing.JLabel genero;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pfp;
    private javax.swing.JLabel seguidoresUsuario;
    private javax.swing.JLabel seguidosUsuario;
    private javax.swing.JButton seguir;
    private javax.swing.JList<String> tweetsUsuario;
    // End of variables declaration//GEN-END:variables
}
